name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ compiler
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: sudo apt-get install g++ make

    - name: Build with Make
      run: make

    - name: Run the executable
      run: ./ZadClassKcpp
